# Application
spring.application.name=spring357-eshop
server.port=${APP_SERVER_PORT}
springdoc.api-docs.path=/api-docs

# PostgreSQL DataSource
spring.datasource.url=${POSTGRES_SERVER_URL}
spring.datasource.username=${POSTGRES_USER_NAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG