redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.project=${REDIS_PROJECT_NAME}
redis.api-test-directory=${REDIS_API_TEST_DIR}
redis.user-directory=${REDIS_USER_DIR}
redis.error-directory=${REDIS_ERROR_DIR}